[build]
  command = "npm run build"
  publish = "out"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Increase the timeout if your builds are timing out
  node_bundler = "esbuild"

# These redirects are required for Next.js with app router
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/image*"
  to = "/.netlify/image-api*"
  status = 200

# Main network subdomain handling
[[redirects]]
  from = "https://testnet.supernovanetwork.xyz/*"
  to = "/testnet/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://explorer.supernovanetwork.xyz/*"
  to = "/explorer/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://status.supernovanetwork.xyz/*"
  to = "/status/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://docs.supernovanetwork.xyz/*"
  to = "/docs/:splat"
  status = 200
  force = true

# Testnet-specific subdomain handling
[[redirects]]
  from = "https://explorer.testnet.supernovanetwork.xyz/*"
  to = "/testnet/explorer/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://status.testnet.supernovanetwork.xyz/*"
  to = "/testnet/status/:splat"
  status = 200
  force = true

# Alternative testnet domain format
[[redirects]]
  from = "https://testnet-explorer.supernovanetwork.xyz/*"
  to = "/testnet/explorer/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://testnet-status.supernovanetwork.xyz/*"
  to = "/testnet/status/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/_not-found"
  status = 404

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false" 