[build]
  command = "npm run build"
  publish = "out"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Increase the timeout if your builds are timing out
  node_bundler = "esbuild"

# These redirects are required for Next.js with app router
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/image*"
  to = "/.netlify/image-api*"
  status = 200

[[redirects]]
  from = "/*"
  to = "/_not-found"
  status = 404

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false" 